version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bizintel_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: bizintel_api
    restart: always
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - INGEST_API_KEY=${INGEST_API_KEY}
    depends_on:
      db:
        condition: service_healthy

  master_worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: bizintel_master_worker
    restart: always
    command: ["python", "workers/scheduler.py"] 
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - GROQAPI=${GROQAPI}
      - PYTHONPATH=/app
      
      - INTERVAL_ETL=2
      - INTERVAL_ML=5
      - INTERVAL_FORECAST=10
      - INTERVAL_DRIFT=10
      - INTERVAL_LLM=15
      
      - TEST_MIN_RECORDS_FORECAST=10
      - TEST_MIN_RECORDS_DRIFT=20
    volumes:
      - ../backend/model_artifacts:/app/model_artifacts
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started

volumes:
  postgres_data:
    driver: local